# Generated by Django 5.0.3 on 2024-09-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_id_alter_departmentimages_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='established_date',
            field=models.DateField(),
        ),
    ]
